run:
  start: '2022-06-17T00:00:00Z'
  stop: '2022-06-18T00:00:00Z'
orekit:
  data: https://gitlab.orekit.org/orekit/orekit-data/-/archive/master/orekit-data-master.zip
aois:
  url: https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip
  #url: https://datahub.io/core/geo-countries/r/countries.geojson
  buffer: 20 km
satellites:
  sat1:
    name: landat-8
    color: green
    groundTrace:
      show: true
      weight: 1.
    filter: true
    catnr: 39084
  sat2:
    name: landsat-9
    color: teal
    groundTrace:
      show: true
      weight: 1.
    filter: true
    tle:
      line1: 1 49260U 21088A   22166.94778099  .00000339  00000+0  85254-4 0  9992
      line2: 2 49260  98.2276 237.1831 0001142  78.2478 281.8849 14.57099002 38060
  sat3:
    name: Test-1
    color: purple
    groundTrace:
      show: true
      weight: 1.
    mission:
      groundTrace: true
      sun: true
      eclipse: false
    keplerian:
      epoch: '2022-06-16T17:54:00Z'
      #semi-major axis (m)
      a: 7080 km
      #eccentricy
      e: 0.0008685
      #inclination
      i: 85 deg
      # raan
      omega: 261.4942 deg
      # argument of perigee
      w: 246.9642 deg
      # true anomaly
      #v:
      # mean anomaly
      m: 257.7333 deg
    lof: qsw
    attitudes:
      - name: mission
        type: LofOffset
        lof: qsw
        default: true
        tx: # transform from LOF
          x: [-1., 0., 0.] # +x_body toward nadir
          z: [0., 1., 0.]  # +z_body toward velocity
    sensors:
      - id: camera
        type: camera
        focalLength: 178 mm
        pitch: 25 um
        imgPeriod: 22 Hz
        cols: 1024
        rows: 768
        rowsAlongX: true #when true rows are along the paylod frame's X axis, when false they align to the Y axis
        frame:
          translation: [0., 0., 0.]
          z: [1, 0, 0]
          x: [0, 1, 0]
      
earth:
  model: wgs84
  frameName: itrf
  iersConventions: iers_2010
  simpleEop: false

control:
  step: PT10M
  multithread: true
